# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MenuWindow(object):
    def setupUi(self, MenuWindow):
        MenuWindow.setObjectName("MenuWindow")
        MenuWindow.resize(400, 300)
        self.background1 = QtWidgets.QLabel(MenuWindow)
        self.background1.setGeometry(QtCore.QRect(0, 0, 401, 301))
        self.background1.setText("")
        self.background1.setPixmap(QtGui.QPixmap("sdfd.png"))
        self.background1.setScaledContents(True)
        self.background1.setObjectName("background1")
        self.beginButton = QtWidgets.QPushButton(MenuWindow)
        self.beginButton.setGeometry(QtCore.QRect(100, 160, 201, 28))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.beginButton.setFont(font)
        self.beginButton.setObjectName("beginButton")
        self.manualButton = QtWidgets.QPushButton(MenuWindow)
        self.manualButton.setGeometry(QtCore.QRect(100, 220, 201, 28))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.manualButton.setFont(font)
        self.manualButton.setObjectName("manualButton")

        self.retranslateUi(MenuWindow)
        QtCore.QMetaObject.connectSlotsByName(MenuWindow)

    def retranslateUi(self, MenuWindow):
        _translate = QtCore.QCoreApplication.translate
        MenuWindow.setWindowTitle(_translate("MenuWindow", "Главное Меню"))
        self.beginButton.setText(_translate("MenuWindow", "НАЧАТЬ"))
        self.manualButton.setText(_translate("MenuWindow", "ИНСТРУКЦИЯ"))
